checks:
    javascript:
        code_rating: true

filter:
    excluded_paths: [/public/js/*]

build:
    environment:
        node: 'v8.4.0'
    tests:
        override:
            -
                command: 'npm run test-scrutinizer'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
