checks:
    javascript:
        code_rating: true

build:
    tests:
        override:
            -
                command: 'npm run test-scrutinizer'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
