language: node_js

sudo: false

notifications:
  email: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
