language: node_js

notifications:
  email: false

services:
    - mongodb

node_js:
    - "node"
    - "7"
    - "8"

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test
